<div class="col-xs-4 col-xs-offset-4">
    <?= $this->flash->output() ?>
    <form action="<?= $this->url->get('signin') ?>" method="post">
        <div class="form-group">
            <input type="text" id="email" name="email" placeholder="Email" class="form-control" />
        </div>
        <div class="form-group">
            <input type="password" id="password" name="password" placeholder="Password" class="form-control" />
        </div>
        <input type="submit" value="OK" class="btn btn-primary" />
    </form>
</div>