<div class="col-xs-4 col-xs-offset-4">
    <?= $this->flash->output() ?>
    <form action="<?= $this->url->get('signin') ?>" method="post">
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="text" id="email" name="email" class="form-control" />
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" class="form-control" />
        </div>
        <div class="form-group">
              <input type="submit" value="OK" class="btn btn-primary" />
        </div>
    </form>
</div>