<div class="row">
    <div class="col-xs-4 col-xs-offset-4">
        <form class="form-inline" method="post" action="<?= $this->url->get('lesson/create') ?>">
            <input type="text" name="name" placeholder="Name" class="form-control" required />
            <input type="submit" value="create" class="btn btn-primary"/>
        </form>
    </div>
</div>
<div class="row">
    <? foreach ($list as $lesson) : ?>
        <div class="col-xs-12"><?= $lesson['name']  ?> |
            <a href="<?= $this->url->get(array('for' => 'run-lesson', 'id' => $lesson['id'], 'set' => 'direct')) ?>">direct</a>
            <a href="<?= $this->url->get(array('for' => 'run-lesson', 'id' => $lesson['id'], 'set' => 'inverse')) ?>">inverse</a> |
            <a href="<?= $this->url->get(array('for' => 'edit-lesson', 'id' => $lesson['id'])) ?>">edit</a>
            <a href="<?= $this->url->get(array('for' => 'delete-lesson', 'id' => $lesson['id'])) ?>">delete</a>
        </div>
    <? endforeach ?>
</div>
