<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf8">
        <title>English Roulette</title>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?= $this->url->get('css/main.css') ?>" />
        
        <!--css-->
        <?= $this->assets->outputCss() ?>
        
    </head>
    <body>
        <header><h1>English Roulette</h1></header>
        
        <div class="container">
            <?= $this->getContent() ?>
        </div>
        
        <footer>English Roulette&COPY; 2015</footer>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?= $this->url->get('js/main.js') ?>"></script>
        
        <!--js-->
        <?= $this->assets->outputJs() ?>
        
    </body>
</html>
